version: "2"


services:    
    lit-app:
        image: $IMAGE:$VERSION
        environment: 
                - PORT=8000
        build:
            context: ./consumer
        ports:
          - "8501:8501"
