version: "2"

services:    
    lit-app:
        image: $IMAGE:$VERSION
        depends_on:
                - fastapi-app
        environment:
                - PORT=8000
        build:
            context: .
            dockerfile: ./consumer/Dockerfile
          
    fastapi-app:
        image: $IMAGE:$VERSION
        environment: 
                - PORT=8005
        build:
            context: .
            dockerfile: ./producer/Dockerfile
        
