name: Test, Docker Image CI & Deploy To Cloud

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  env: 
      HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }} 
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: docker build . -f Dockerfile -t registry.heroku.com/$HEROKU_APP_NAME/web
      
    - name: Login to Heroku Container registry
      run: heroku container:login
      
    - name: Build and push
      # run: heroku container:push -a $HEROKU_APP_NAME web
      run: docker push registry.heroku.com/$HEROKU_APP_NAME/web:latest  
      
  deploy:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v3
    - name: Release
      run: heroku container:release -a $HEROKU_APP_NAME web
      
